### ISSUE TITLE
News Filter

### ISSUE THREAD

**Issue by aaronpcz** [vered1986/Chirps#2]
Hi, I'd like to know a bit more about what news filter you used within the TwitterSearch package?

**Comment by vered1986** [comment]
We simply added `url += '&filter=news'` to the search URL. Specifically, it was added to `create_search_url()` in `TwitterSearchOrder.py` of the TwitterSearch tool (right before this line: https://github.com/ckoepp/TwitterSearch/blob/master/TwitterSearch/TwitterSearchOrder.py#L251).
